GET http://localhost:3009/school-dashboard/transactions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODIwZmQ0ZGFjMmE1ODY2N2Q4MDY5MiIsImlhdCI6MTczNjU5MDg3MSwiZXhwIjoxNzM3MTk1NjcxfQ.kN72NK02R1EW9BGrJ_P_cEggfYTF7VbKtzxdPHpG0ag



###
POST http://localhost:3009/school-dashboard/add-transaction
Content-Type: application/json

{
    "_id":  "6730d9b926c65c39b0ee0149",
   "school_id": "67308b27e9bbcdf5f22d24c1",
   "trustee_id": "66505181ca3e97e19f142076",
   "gateway": "CASHFREE",
   "order_amount": 10000,
   "custom_order_id": "test1"
}

###
POST http://localhost:3009/school-dashboard/add-status
Content-Type: application/json

{
      "collect_id": "6730d9b926c65c39b0ee0149",
      "status": "SUCCESS",
      "payment_method": "upi",
      "gateway": "CASHFREE",
      "transaction_amount": 10100,
      "bank_refrence": "YESBNK221"
}


###
GET http://localhost:3009/school-dashboard/check-status/test2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODIwZmQ0ZGFjMmE1ODY2N2Q4MDY5MiIsImlhdCI6MTczNjU5MDg3MSwiZXhwIjoxNzM3MTk1NjcxfQ.kN72NK02R1EW9BGrJ_P_cEggfYTF7VbKtzxdPHpG0ag

###
POST http://localhost:3009/school-dashboard/signup
Content-Type: application/json

{
      "username": "jesus",
      "email": "jesus@gmail.com",
      "password": "123456"
}


###
POST http://localhost:3009/school-dashboard/login
Content-Type: application/json

{
      "email": "king@gmail.com",
      "password": "123456"
}